### ISSUE TITLE
Wide camera

### ISSUE THREAD

**Issue by zhenyolka** [ivecera/miuicamera_pyxis#2]
Hi! Thanks for good miui camera port. All works, but can't find wide camera button. Will you add support of it?

**Comment by ivecera** [comment]
Yes, I'm planning to enable support for ultrawide lens as well as another features. Of course one can use ANX Camera but many people have a bad experience (FC, crashes) with it due to missing flashable fixes that are specific for each device or need to set feature options properly. Enthusiasts usually know how to do it or are able to find proper instructions but this is not for ordinary user that just want to install the application and use it.

My goal is to have a stable Miui Camera for Mi 9 Lite (pyxis) with all possible and stable features that will work out of box.

**Comment by zhenyolka** [comment]
Thanks. Your port is really good. Works perfect. If it possible (I know miui cam don't support this) add raw photo mode. Now no camera app can't do raw with 48mp. This mode will be really good.
